# R packages to install in Docker container
# Generated from local Windows R installation

packages <- c(
  # "abind",
  # "additivityTests",
  # "anytime",
  # "ape",
  # "aplot",
  "arrow",
  # "ash",
  # "AsioHeaders",
  # "askpass",
  # "assertthat",
  # "attempt",
  # "automagic",
  # "av",
  # "AzureAuth",
  # "AzureGraph",
  # "AzureRMR",
  # "AzureStor",
  # "backports",
  # "base64enc",
  # "base64url",
  # "BH",
  # "biclust",
  # "binr",
  # "bit",
  # "bit64",
  # "bitops",
  # "blob",
  # "blotter",
  "brew",
  # "brio",
  # "broom",
  # "broom.helpers",
  "bsicons",
  "bslib",
  # "ca",
  # "cachem",
  "callr",
  "canvasXpress",
  "car",
  "carData",
  # "cards",
  "caret",
  # "caTools",
  # "cellranger",
  # "checkmate",
  # "chromote",
  "chron",
  # "circlize",
  # "classInt",
  "cli",
  "clipr",
  # "clisymbols",
  # "clock",
  # "clue",
  "ClustOfVar",
  # "collections",
  # "colorspace",
  # "commonmark",
  # "config",
  # "conflicted",
  # "coro",
  "corrplot",
  "corrr",
  # "covr",
  # "cowplot",
  "cpp11",
  "crayon",
  # "credentials",
  # "crosstalk",
  # "crsmeta",
  # "crul",
  "curl",
  # "cyclocomp",
  "data.table",
  # "data.tree",
  "DataExplorer",
  "DBI",
  "dbplyr",
  # "deldir",
  # "dendextend",
  # "Deriv",
  "desc",
  # "devtools",
  # "diagram",
  # "dials",
  # "DiceDesign",
  # "diffobj",
  # "digest",
  # "doBy",
  # "doFuture",
  # "doParallel",
  # "dotCall64",
  # "downlit",
  "dplyr",
  # "dqrng",
  "DT",
  "dtplyr",
  # "dynamicTreeCut",
  # "e1071",
  # "effsize",
  "ellipse",
  "ellipsis",
  # "emmeans",
  # "estimability",
  # "evaluate",
  # "exactRankTests",
  # "expm",
  # "extrafont",
  # "extrafontdb",
  # "factoextra",
  # "FactoMineR",
  # "fansi",
  # "farver",
  # "fastcluster",
  # "fastDummies",
  # "fastmap",
  # "fastmatch",
  # "FinancialInstrument",
  "firebase",
  # "fitdistrplus",
  # "flashClust",
  # "flexclust",
  # "float",
  # "FNN",
  "fontawesome",
  "fontBitstreamVera",
  "fontLiberation",
  "fontquiver",
  "forcats",
  # "foreach",
  "forecast",
  # "formatR",
  # "Formula",
  # "fracdiff",
  # "fs",
  "fst",
  # "fstcore",
  "furrr",
  # "futile.logger",
  # "futile.options",
  # "future",
  # "future.apply",
  # "gargle",
  # "gclus",
  # "gdata",
  # "gdtools",
  # "generics",
  # "gert",
  # "GetoptLong",
  "GGally",
  # "ggalt",
  # "gganimate",
  # "ggflowchart",
  # "ggforce",
  # "ggfun",
  # "ggimage",
  # "ggiraph",
  # "ggmap",
  # "ggnewscale",
  "ggplot2",
  "ggplotify",
  "ggpubr",
  "ggraph",
  "ggrepel",
  "ggridges",
  "ggsci",
  "ggsignif",
  "ggstats",
  "ggtext",
  "ggupset",
  "ggwordcloud",
  "gh",
  "gitcreds",
  "glmnet",
  "GlobalOptions",
  "globals",
  "glue",
  # "gmodels",
  # "goftest",
  # "golem",
  # "googledrive",
  # "googlesheets4",
  # "gower",
  # "GPArotation",
  # "GPfit",
  # "gplots",
  # "graphlayouts",
  # "gridExtra",
  # "gridGraphics",
  # "gridtext",
  # "gson",
  # "gsubfn",
  # "gtable",
  # "gtools",
  # "hardhat",
  # "haven",
  # "here",
  "hexbin",
  "hexSticker",
  # "highr",
  # "Hmisc",
  # "hms",
  "htmlTable",
  "htmltools",
  "htmlwidgets",
  "httpcode",
  "httpgd",
  "httpuv",
  "httr",
  "httr2",
  # "ica",
  # "ids",
  # "igraph",
  # "ini",
  # "ipred",
  # "irlba",
  # "isoband",
  # "ISOcodes",
  # "iterators",
  "janitor",
  # "jose",
  "jpeg",
  "jquerylib",
  "jsonlite",
  "kableExtra",
  # "km.ci",
  # "KMsurv",
  # "knitr",
  # "labeling",
  # "labelled",
  # "lambda.r",
  "languageserver",
  # "later",
  # "lava",
  # "lazyeval",
  "leaflet",
  "leaflet.providers",
  # "leaps",
  # "leiden",
  # "lgr",
  # "lhs",
  # "lifecycle",
  # "lintr",
  # "listenv",
  # "litedown",
  # "lme4",
  # "lmtest",
  # "lobstr",
  # "locfit",
  # "lpSolve",
  # "lubridate",
  # "magick",
  "magrittr",
  # "mallet",
  # "maps",
  "markdown",
  "markovchain",
  "MatrixExtra",
  "MatrixModels",
  "matrixStats",
  "maxstat",
  "mcptools",
  # "memoise",
  # "microbenchmark",
  # "mime",
  # "miniUI",
  # "minqa",
  # "mitools",
  # "mlapi",
  # "mnormt",
  # "modelenv",
  # "ModelMetrics",
  # "modelr",
  # "modeltools",
  # "moments",
  # "multcompView",
  # "munsell",
  # "mvtnorm",
  # "nanonext",
  # "networkD3",
  # "ngram",
  # "nloptr",
  # "numDeriv",
  "odbc",
  "ollamar",
  "openai",
  # "openalexR",
  "openssl",
  "openxlsx",
  # "osmdata",
  # "otel",
  # "otp",
  # "overlapping",
  "pacman",
  "pak",
  "pander",
  # "parallelly",
  # "parsnip",
  # "patchwork",
  # "pbapply",
  # "pbkrtest",
  # "PCAmixdata",
  # "PerformanceAnalytics",
  # "permute",
  # "pillar",
  "pkgbuild",
  "pkgconfig",
  "pkgdown",
  "pkgload",
  "pkgsearch",
  # "plogr",
  "plotly",
  "plyr",
  "png",
  "polished",
  # "polyclip",
  # "polynom",
  # "praise",
  # "prettyunits",
  "pROC",
  # "processx",
  # "prodlim",
  # "profvis",
  # "progress",
  # "progressr",
  # "PROJ",
  # "proj4",
  # "promises",
  # "proto",
  # "proxy",
  # "pryr",
  # "ps",
  # "psych",
  "purrr",
  # "qap",
  # "quadprog",
  "quantmod",
  # "quantreg",
  # "quantstrat",
  # "R.cache",
  # "R.methodsS3",
  # "R.oo",
  "R.utils",
  # "R6",
  # "ragg",
  "randomForest",
  "RANN",
  # "rappdirs",
  # "rapportools",
  # "raster",
  # "rbibutils",
  # "rcmdcheck",
  "RColorBrewer",
  # "Rcpp",
  # "RcppAnnoy",
  # "RcppArmadillo",
  # "RcppEigen",
  # "RcppHNSW",
  # "RcppParallel",
  # "RcppProgress",
  # "RcppTOML",
  # "rcrossref",
  # "RCurl",
  # "Rdpack",
  "readr",
  "readxl",
  "recipes",
  # "reformulas",
  # "registry",
  # "rematch",
  # "rematch2",
  # "remotes",
  # "repr",
  # "reprex",
  # "reproj",
  # "reshape2",
  "reticulate",
  "rex",
  # "RhpcBLASctl",
  # "rJava",
  # "rjson",
  # "rlang",
  "rmarkdown",
  "ROCit",
  "ROCR",
  "roxygen2",
  "Rprofet",
  # "rprojroot",
  # "rsample",
  # "rsparse",
  # "RSpectra",
  "RSQLite",
  # "rstatix",
  # "rstudioapi",
  # "rsvd",
  # "Rtsne",
  # "Rttf2pt1",
  # "rversions",
  # "rvest",
  # "s2",
  # "S7",
  # "safetensors",
  # "sass",
  # "scales",
  # "scattermore",
  # "scatterpie",
  # "scatterplot3d",
  # "scorecard",
  # "sctransform",
  # "secretbase",
  # "selectr",
  # "seriation",
  # "sessioninfo",
  # "SeuratObject",
  # "sf",
  # "sfd",
  # "shadowtext",
  # "shape",
  "shiny",
  "shinyAce",
  "shinyalert",
  "shinyBS",
  "shinybusy",
  "shinycssloaders",
  "shinydashboard",
  "shinyFeedback",
  "shinyjqui",
  "shinyjs",
  "shinyWidgets",
  # "showtext",
  # "showtextdb",
  # "signal",
  # "sitmo",
  # "skimr",
  # "slider",
  # "snakecase",
  # "snow",
  # "sodium",
  # "sourcetools",
  # "sp",
  # "spam",
  # "SparseM",
  # "sparsevctrs",
  # "spatstat.data",
  # "spatstat.explore",
  # "spatstat.geom",
  # "spatstat.random",
  # "spatstat.sparse",
  # "spatstat.univar",
  # "spatstat.utils",
  "sqldf",
  # "SQUAREM",
  # "statmod",
  # "stopwords",
  # "stringi",
  # "stringr",
  # "styler",
  # "summarytools",
  # "survey",
  # "survMisc",
  # "svglite",
  # "swagger",
  # "sys",
  # "sysfonts",
  # "systemfonts",
  # "tableone",
  # "tailor",
  # "tensor",
  # "tensorflow",
  # "terra",
  # "testthat",
  # "text",
  # "text2vec",
  # "textmineR",
  # "textshaping",
  # "tfautograph",
  # "tfruns",
  "tibble",
  "tidygraph",
  "tidyr",
  "tidyselect",
  "tidytree",
  "tidyverse",
  "timechange",
  "timeDate",
  "tinytex",
  "tippy",
  "topics",
  "torch",
  "transformr",
  # "triebeard",
  # "tseries",
  # "TSP",
  # "TTR",
  # "tune",
  # "tuneR",
  # "tweenr",
  # "tzdb",
  # "unigd",
  # "units",
  # "urca",
  # "urlchecker",
  # "urltools",
  # "usethis",
  "utf8",
  "uuid",
  # "uwot",
  # "vctrs",
  # "vegan",
  # "viridis",
  # "viridisLite",
  # "visNetwork",
  # "vroom",
  # "waldo",
  # "warp",
  # "websocket",
  # "webutils",
  # "WGCNA",
  # "whisker",
  # "withr",
  # "wk",
  # "workflows",
  # "writexl",
  # "xefun",
  # "xfun",
  "xgboost",
  "XML",
  "xml2",
  # "xmlparsedata",
  # "xopen",
  "xtable",
  # "xts",
  "yaml",
  # "yardstick",
  # "yulab.utils",
  # "zeallot",
  # "zip",
  "zoo"
)

# Set up repositories (CRAN + r-universe for btw/ellmer)
options(repos = c(
  "posit-dev" = "https://posit-dev.r-universe.dev",
  CRAN = "https://cloud.r-project.org"
))

# Install packages
cat("Installing CRAN packages...\n")
for (pkg in packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    tryCatch({
      install.packages(pkg, dependencies = TRUE)
    }, error = function(e) {
      message(paste("Failed to install:", pkg, "-", e$message))
    })
  }
}

cat("Package installation complete!\n")
